#!/bin/bash

# ENVIRONMENT
xset -b # turn off beeps
xset dpms 120 120 120 # turn off display after 2 minutes
#/usr/bin/xmodmap ${HOME}/.local/src/dotfiles/.Xmodmap

if xrandr | grep -q "DP1 connected"; then
  sudo desktop_configuration
else
  sudo laptop_configuration
fi

# DAEMONS
~/.dropbox-dist/dropbox &
~/.local/bin2/ssh_agent &
autokey-gtk &
flameshot &
unclutter &

# APPS
/usr/local/bin/st &
firefox &

exec /usr/bin/fluxbox
