#!/bin/bash
xcompmgr &
pidgin &
audacious2 &
~/.dropbox-dist/dropboxd &

xset -b # turn off beeps
numlockx on &
unclutter -root &
/usr/bin/gnome-do &
tomboy &
firefox &
ssh-agent &
urxvtd &
/opt/dropbox/dropboxd &

#### KEEP THE CLIPBOARDS IN SYNC
# a bit of a hack so I can paste from Chrome text boxes into my shell.
autocutsel -s CLIPBOARD &
autocutsel -s PRIMARY &

exec /usr/bin/fluxbox
