#!/bin/bash

# ENVIRONMENT
xset -b # turn off beeps
xcompmgr &
numlockx on &
unclutter -root &
~/dotfiles/bin/clipboard-sync.sh

# APPS
pidgin &
audacious2 &
gnome-do &
tomboy &
chrome &
urxvtd &
/opt/dropbox/dropboxd &

exec /usr/bin/fluxbox
