#!/usr/bin/env bash
packages=(
  autoconf
  autogen
  automake
  awscli
  bash
  bash-completion
  bdw-gc
  cmake
  coreutils
  fzf
  git
  gmp
  gnu-sed
  gnupg2
  guile
  htop
  imagemagick
  jq
  jshon
  libevent
  libffi
  libtool
  libunistring
  mobile-shell
  openssl
  parallel
  pcre
  pidof
  pkg-config
  protobuf
  python3
  readline
  reattach-to-user-namespace
  redis
  rename
  the_silver_searcher
  tig
  tmux
  tree
  watch
  wget
  xz
  zlib
)

casks=(
  imageoptim
  java
)

installed_packages=( $(brew list -1) )
installed_casks=( $(brew cask list -1) )

for p in ${packages[@]}; do
  found=false
  for i in ${installed_packages[@]}; do
    [[ "$p" == "$i" ]] && found=true
  done
  $found || brew install $p
done

for c in ${casks[@]}; do
  found=false
  for i in ${installed_casks[@]}; do
    [[ "$c" == "$i" ]] && found=true
  done
  $found || brew cask install $c
done
